Repository datacite/lupo, pull requests merged in 2020-06, with the labels that each got.

#562 Fix elasticsearch pagination in GraphQL API
  app/graphql/connections/elasticsearch_model_response_connection.rb
  app/graphql/types/doi_item.rb
  app/models/concerns/indexable.rb
  app/models/doi.rb
  spec/graphql/types/book_chapter_type_spec.rb
  spec/graphql/types/book_type_spec.rb
  spec/graphql/types/dataset_type_spec.rb
  spec/graphql/types/dissertation_type_spec.rb
  spec/graphql/types/instrument_type_spec.rb
  spec/graphql/types/journal_article_type_spec.rb
  spec/graphql/types/member_type_spec.rb
  spec/graphql/types/peer_review_type_spec.rb
  spec/graphql/types/preprint_type_spec.rb
  spec/graphql/types/repository_type_spec.rb
  spec/graphql/types/service_type_spec.rb
  spec/graphql/types/work_type_spec.rb
  spec/requests/dois_spec.rb
Labels: bug

#570 use correct sqs queue
  app/models/concerns/indexable.rb
  config/application.rb
Labels: bug

#492 [Proposal] new rake tasks for meta operations
  lib/tasks/data_layer.rake
  lib/tasks/elasticsearch.rake
Labels: feature, needs review

#571 fix: add relation between key and test
  app/graphql/types/year_month_total_type.rb
  spec/graphql/types/dataset_type_spec.rb
Labels: needs review
